### ISSUE TITLE
changed token is not updated

### ISSUE THREAD

**Issue by azrdev** [stdevel/ansible-sentinelone_client#1]
due to 
https://github.com/stdevel/ansible-sentinelone_client/blob/367968cb32594063f473bc4efe1b9a94c666ba03/tasks/main.yml#L34-L37

finding that /opt/sentinelone/.INITIALIZATION_COMPLETE already exists

**Comment by stdevel** [comment]
Hi @azrdev,
@chrisvanmeer supplied a PR for your request - looks good to me.

What do you think? Do you want to have a look at it?
