### ISSUE TITLE
Signed packages since version 23.3.2.12

### ISSUE THREAD

**Issue by chrisvanmeer** [stdevel/ansible-sentinelone_client#6]
Since I found the unsigned part pretty awkward, considering this is a security product, I raised a ticket and was reported the following.

> Please note that the version `23.3.2.12` is a signed version and there are no more unsigned versions than this version. Please use the commands without the `--nodigest`

I tried to install this version on a RHEL8 client, when removing the `--nodigest` from the following line

https://github.com/stdevel/ansible-sentinelone_client/blob/ccf4e98235283d1e522b3b48566db3de38228a0b/tasks/install_redhat.yml#L11

This worked fine.  
So the question arises, how can we detect the version and according to the version either use or leave out the `--nodigest` part.

**Comment by stdevel** [comment]
Hi @chrisvanmeer,
thanks for the information - good to see they finally managed to sign their packages. 🙏🏻 

I think we should be use the `version()` filter for this: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/version_test.html#examples

Will investigate in branch `feat-version_check-6`.

**Comment by stdevel** [comment]
I just added a check and successfully tested it with version 23.1.2.9 and 23.3.2.12. Do you want to have a look at it?

**Caution**, as there is a breaking change. The variable name prefix `sentinelone_` becomes `sentinelone_client_`.

**Comment by chrisvanmeer** [comment]
Was handled by https://github.com/stdevel/ansible-sentinelone_client/pull/7
